In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

data=pd.read_csv('/content/beer-servings.csv',index_col='Unnamed: 0')
data.head()

,country,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol,continent
0,Afghanistan,0.0,0.0,0.0,0.0,Asia
1,Albania,89.0,132.0,54.0,4.9,Europe
2,Algeria,25.0,0.0,14.0,0.7,Africa
3,Andorra,245.0,138.0,312.0,12.4,Europe
4,Angola,217.0,57.0,45.0,5.9,Africa

In [2]:
data.isna().sum()

country                         0
beer_servings                   8
spirit_servings                 8
wine_servings                   6
total_litres_of_pure_alcohol    1
continent                       0
dtype: int64

In [3]:
for i in ['beer_servings', 'spirit_servings', 'wine_servings',
       'total_litres_of_pure_alcohol']:
      data[i]=data[i].fillna(data[i].median())

In [4]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 193 entries, 0 to 192
Data columns (total 6 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   country                       193 non-null    object
 1   beer_servings                 193 non-null    float64
 2   spirit_servings               193 non-null    float64
 3   wine_servings                 193 non-null    float64
 4   total_litres_of_pure_alcohol  193 non-null    float64
 5   continent                     193 non-null    object
dtypes: float64(4), object(2)
memory usage: 10.6+ KB

In [5]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()

In [6]:
data['continent']=le.fit_transform(data['continent'])

In [7]:
data.head()

,country,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol,continent
0,Afghanistan,0.0,0.0,0.0,0.0,1
1,Albania,89.0,132.0,54.0,4.9,2
2,Algeria,25.0,0.0,14.0,0.7,0
3,Andorra,245.0,138.0,312.0,12.4,2
4,Angola,217.0,57.0,45.0,5.9,0

In [8]:
data['country']=le.fit_transform(data['country'])

In [9]:
data.head()

,country,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol,continent
0,0,0.0,0.0,0.0,0.0,1
1,1,89.0,132.0,54.0,4.9,2
2,2,25.0,0.0,14.0,0.7,0
3,3,245.0,138.0,312.0,12.4,2
4,4,217.0,57.0,45.0,5.9,0

In [24]:
df=pd.read_csv('/content/beer-servings.csv',index_col='Unnamed: 0')
df.head()

,country,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol,continent
0,Afghanistan,0.0,0.0,0.0,0.0,Asia
1,Albania,89.0,132.0,54.0,4.9,Europe
2,Algeria,25.0,0.0,14.0,0.7,Africa
3,Andorra,245.0,138.0,312.0,12.4,Europe
4,Angola,217.0,57.0,45.0,5.9,Africa

In [25]:
for i in ['beer_servings', 'spirit_servings', 'wine_servings',
       'total_litres_of_pure_alcohol']:
      df[i]=data[i].fillna(data[i].median())

In [26]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 193 entries, 0 to 192
Data columns (total 6 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   country                       193 non-null    object
 1   beer_servings                 193 non-null    float64
 2   spirit_servings               193 non-null    float64
 3   wine_servings                 193 non-null    float64
 4   total_litres_of_pure_alcohol  193 non-null    float64
 5   continent                     193 non-null    object
dtypes: float64(4), object(2)
memory usage: 10.6+ KB

In [27]:
df=pd.get_dummies(df,dtype='int32')

In [28]:
df.head(10)

,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol,country_Afghanistan,country_Albania,country_Algeria,country_Andorra,country_Angola,country_Antigua & Barbuda,...,country_Vietnam,country_Yemen,country_Zambia,country_Zimbabwe,continent_Africa,continent_Asia,continent_Europe,continent_North America,continent_Oceania,continent_South America
0,0.0,0.0,0.0,0.0,1,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
1,89.0,132.0,54.0,4.9,0,1,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
2,25.0,0.0,14.0,0.7,0,0,1,0,0,0,...,0,0,0,0,1,0,0,0,0,0
3,245.0,138.0,312.0,12.4,0,0,0,1,0,0,...,0,0,0,0,0,0,1,0,0,0
4,217.0,57.0,45.0,5.9,0,0,0,0,1,0,...,0,0,0,0,1,0,0,0,0,0
5,102.0,128.0,45.0,4.9,0,0,0,0,0,1,...,0,0,0,0,0,0,0,1,0,0
6,76.0,25.0,221.0,8.3,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
7,21.0,179.0,11.0,3.8,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
8,261.0,72.0,212.0,10.4,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
9,279.0,75.0,191.0,9.7,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0